version: "3"
services:
  api:
    image: node:16.15.1

    working_dir: /triviani-trivia-app-SERVER
    volumes:
      - type: bind
        source: ./
        target: /triviani-trivia-app-SERVER

  db:
    image: postgres:12.4
    environment:
      - POSTGRES_USER=futureproof
    volumes:
      - './database:/docker-entrypoint-initdb.d/:ro'
